### ISSUE TITLE
Backup/Restore tasks fail for configuration groups

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/sastre#12]
1. On test vManage go to Workflows -> Create Configuration Group and follow the workflow to create test config group.
2. Run: sdwan --verbose backup all --workdir test
3. Run: sdwan --verbose delete all
4. Run: sdwan --verbose restore all --workdir test

The command will fail with:
ERROR: Failed: Create SDWAN transport profile test_WAN: 4 validation errors for ProfileParcelModel
payload -> data
  field required (type=value_error.missing)
subparcels -> 0 -> payload -> data
  field required (type=value_error.missing)
subparcels -> 1 -> payload -> data
  field required (type=value_error.missing)
subparcels -> 2 -> payload -> data
  field required (type=value_error.missing)
ERROR: Failed: Create SDWAN service profile test_LAN: 2 validation errors for ProfileParcelModel
payload -> data
  field required (type=value_error.missing)
subparcels -> 0 -> payload -> data
  field required (type=value_error.missing)
ERROR: Failed: Create SDWAN system profile test_Basic: 1 validation error for ProfileParcelModel
payload -> data
  field required (type=value_error.missing)
INFO: Done: Create configuration group test
INFO: Task completed with caveats: 3 errors

**Comment by reismarcelo** [comment]
Hi, thanks for reporting this and the PR. On which vManage release did you encounter this issue?

**Comment by tzarski0** [comment]
Hi @reismarcelo, the PR is for a different issue. I tested this issue on 20.12.2 and 20.13.1 and it fails on both. I think problem is with backup task. When I see the JSON output of backup in feature profile, I see in the payload that "name" and "description" is present, but "data" field is missing.

**Comment by reismarcelo** [comment]
Fixed in dev-1.24
