### ISSUE TITLE
Migrate to pydanticv2

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/sastre#15]
Right now, the pydantic<2 is listed as dependency. This makes it hard to use sastre with any other packages which are already on pydantic > 2 (for example official Python SDK catalystwan). Ask is to migrate sastre to pydantic>2.

**Comment by reismarcelo** [comment]
Definitely, this is coming in 1.23 version. Planned for end of Feb/24

**Comment by tzarski0** [comment]
Thanks!
