### ISSUE TITLE
ERROR - Failed backup configuration group <name> automated rules

### ISSUE THREAD

**Issue by tzarski0** [CiscoDevNet/sastre#17]
When doing backup of configuration groups in 20.12, the following log is printed:
ERROR - Failed backup configuration group edge_basic automated rules

The API Path in sastre is "tag/tagRules/{configGroupId}", but when I try this API call in vManage, it returns 301 Moved Pernamently with message: 
{
  "Note": "Please use the new endpoint-  v1/config-group/{configGroupId}/rules"
}

**Comment by reismarcelo** [comment]
Fixed in dev-1.24
